/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.LinkedList;
import java.util.stream.Collectors;
public class App {
public static void main(String[] args) throws IOException {
        String sign = "x";
        Integer suma=0;
        App app=new App();  
        LinkedList<String> fileLines = app.openFile();
            for(int i=0;i<fileLines.size();i++) {
                String[] stringArray = fileLines.get(i).split("x");
                if (stringArray.length != 3)
                    continue;
                Integer pole1 = Integer.valueOf(stringArray[0]) * Integer.valueOf(stringArray[1]);
                Integer pole2 = Integer.valueOf(stringArray[1]) * Integer.valueOf(stringArray[2]);
                Integer pole3 = Integer.valueOf(stringArray[2]) * Integer.valueOf(stringArray[0]);
                Integer minPole = min(pole1, pole2, pole3);
                suma = suma + 2 * pole1 + 2 * pole2 + 2 * pole3 + minPole;
            }
            System.out.println("Pole calkowite= "+suma+" dm2");
        
    }
    private LinkedList<String> openFile(){
        InputStream in = getClass().getResourceAsStream("/dane.txt");
        BufferedReader reader = new BufferedReader(new InputStreamReader(in));
        return reader.lines().collect(Collectors.toCollection(LinkedList::new));
    }
	
	static Integer min(Integer... tab ){
		Integer minValue=tab[0];
		for(Integer val:tab){
			if(minValue>val){
				minValue=val;
			}
		}
		return minValue;
	}

}
